version: '3'

services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app-network
    volumes:
      - redis:/data/stompsdb

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    networks:
      - app-network
    volumes:
      - mongo-data:/data/stompsdb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - '3000:3000'
    networks:
      - app-network
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started


networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  redis: