version: '3'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/stompsdb

  redis:
    image: redis
    restart: always
    # ports:
      # - '6370:6370'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

volumes:
  mongo-data:
