version: '3'

services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app-network
    volumes:
      - redis:/data/stompsdb

  mongo:
    image: mongo
    restart: always
    networks:
      - app-network
    volumes:
      - mongo-data:/data/stompsdb

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    ports:
      - '3000:3000'
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - mongo
      - redis

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  redis: