version: '3'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/stompsdb

  redis:
    image: redis
    restart: always
    ports:
      - '6370:6370'
    volumes:
      - redis:/data/stompsdb

  app:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - '80:80'
    env_file:
      - .env
    depends_on:
      - mongo
      # - redis

volumes:
  mongo-data:
  redis: